import { z } from 'zod';

export const surveySchema = z.object({
  name: z.string().optional(),
  age: z.coerce.number().min(1, 'Age is required.'),
  gender: z.string().min(1, 'Gender is required.'),
  genderOther: z.string().optional(),
  education: z.string().min(1, 'Educational qualification is required.'),
  maritalStatus: z.string().min(1, 'Marital status is required.'),
  employmentStatus: z.string().min(1, 'Employability status is required.'),
  dp_1: z.string().min(1, 'This field is required.'),
  dp_2: z.string().min(1, 'This field is required.'),
  dp_3: z.string().min(1, 'This field is required.'),
  dp_4: z.string().min(1, 'This field is required.'),
  dp_5: z.string().min(1, 'This field is required.'),
  dp_6: z.string().min(1, 'This field is required.'),
  dp_7: z.string().min(1, 'This field is required.'),
  dp_8: z.string().min(1, 'This field is required.'),
  dp_9: z.string().min(1, 'This field is required.'),
  dp_10: z.string().min(1, 'This field is required.'),
  dp_11: z.string().min(1, 'This field is required.'),
  dp_12: z.string().min(1, 'This field is required.'),
  dp_13: z.string().min(1, 'This field is required.'),
  dp_14: z.string().min(1, 'This field is required.'),
  dp_15: z.string().min(1, 'This field is required.'),
  ocb_1: z.string().min(1, 'This field is required.'),
  ocb_2: z.string().min(1, 'This field is required.'),
  ocb_3: z.string().min(1, 'This field is required.'),
  ocb_4: z.string().min(1, 'This field is required.'),
  ocb_5: z.string().min(1, 'This field is required.'),
  ocb_6: z.string().min(1, 'This field is required.'),
  ocb_7: z.string().min(1, 'This field is required.'),
  ocb_8: z.string().min(1, 'This field is required.'),
  ocb_9: z.string().min(1, 'This field is required.'),
  ocb_10: z.string().min(1, 'This field is required.'),
  ocb_11: z.string().min(1, 'This field is required.'),
  ocb_12: z.string().min(1, 'This field is required.'),
  ocb_13: z.string().min(1, 'This field is required.'),
  ocb_14: z.string().min(1, 'This field is required.'),
  ocb_15: z.string().min(1, 'This field is required.'),
}).refine(data => data.gender !== 'other' || (data.gender === 'other' && data.genderOther && data.genderOther.length > 0), {
  message: "Please specify your gender",
  path: ["genderOther"],
});

export type SurveySchema = z.infer<typeof surveySchema>;
